### ISSUE TITLE
Bug: [1.19.4] Aether causes certain chunks to become invisible (overworld)

### ISSUE THREAD

**Issue by EvergreenSystems** [Gilded-Games/The-Aether#1293]
### What Feature Types Apply to This Bug?

World-Gen, Other (Please Describe)

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.50

### The Aether Version

1.19.4-1.0.0-beta.1-forge

### Steps to Reproduce

Seems to happen 1 out of every 2 or 3 world loads
1. Join/create a world or server
2. Explore the overworld

### What You Expect To Happen

Generation as normal

### What Actually Happened

The Aether appears to be causing random chunks in the overworld to become invisible; they still behave otherwise as expected (you can walk in/interact with them), but they do not render at all.
![2023-05-04_09 30 01](https://user-images.githubusercontent.com/23658767/236240731-b968f57f-6e7d-4a5f-ba03-3d9e96c74412.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Cinex20** [comment]
That's an issue with Rubidium's biome blend.

**Comment by EvergreenSystems** [comment]
Ah so it is, interesting that the issue does not crop up until Aether is added to the mix. Fixed by reducing biome blend to 0, thanks

**Comment by bconlon1** [comment]
It's caused by a Rubidium bug still, I made a PR fix for them on their repo it just needs to be merged.
